=== SChudakov/FirstLab/xml/student_government_events.xsd
<?xml version = "1.0" encoding = "utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="sschudakov" targetNamespace="sschudakov">
    <element name="events" type="tns:events"/>

    <complexType name="events">
        <sequence>
            <element name="event" type="tns:event" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="event">
        <sequence>
            <element name="last_firs_middle_names" type="tns:last_firs_middle_names"/>
            <element name="faculty" type="string"/>
            <element name="sub-faculty" type="string"/>
            <element name="branch-of-study" type="string"/>
            <element name="time" type="tns:time"/>
        </sequence>
    </complexType>

    <complexType name="last_firs_middle_names">
        <sequence>
            <element name="first_name" type="string"/>
            <element name="last_name" type="string"/>
            <element name="middle_name" type="string"/>
        </sequence>
    </complexType>

    <complexType name="time">
        <sequence>
            <element name="begin" type="dateTime"/>
            <element name="end" type="dateTime"/>
        </sequence>
    </complexType>
</schema>

=== SChudakov/FirstLab/xml/student_government_events.xml
<?xml version = "1.0" encoding = "utf-8"?>
<tns:events xmlns:tns="sschudakov"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="sschudakov student_government_events.xsd">

    <event>
        <last_first_middle_name>
            <first_name>Semen</first_name>
            <middle_name>GoodMen</middle_name>
            <last_name>Chudakov</last_name>
        </last_first_middle_name>
        <faculty>Cybernetics</faculty>
        <sub-faculty>Computer Sciences</sub-faculty>
        <branch-of-study>Computer Sciences</branch-of-study>
        <time>
            <begin>2001-10-26T21:32:52</begin>
            <end>2001-10-26T21:32:52</end>
        </time>
    </event>
    
    <event>
        <last_first_middle_name>
            <first_name>Andrey</first_name>
            <middle_name>Borzyak</middle_name>
            <last_name>Andryuha</last_name>
        </last_first_middle_name>
        <faculty>Cybernetics</faculty>
        <sub-faculty>Computer Sciences</sub-faculty>
        <branch-of-study>Informatic</branch-of-study>
        <time>
            <begin>2003-10-14T09:00:00</begin>
            <end>2003-11-14T10:00:00</end>
        </time>
    </event>
    
    <event>
        <last_first_middle_name>
            <first_name>Andrey</first_name>
            <middle_name>Miroshnichenko</middle_name>
            <last_name>Mirosh</last_name>
        </last_first_middle_name>
        <faculty>Red bulk</faculty>
        <sub-faculty>juriprudence</sub-faculty>
        <branch-of-study>law</branch-of-study>
        <time>
            <begin>2003-10-14T14:00:00</begin>
            <end>2010-10-14T09:00:00</end>
        </time>
    </event>
</tns:events>
